### ISSUE TITLE
Can not generate html markdown and collections coreectly 

### ISSUE THREAD

**Issue by abduljeleelng** [knuckleswtf/scribe-js#10]
**What happened?**
1. I set my configuration to...
2. Then I ran `npx scribe:generate` ...
3. But I saw
ⓘ Writing docs...
✖ Writing HTML docs
◼ Writing Postman collection
◼ Writing OpenAPI spec
Error: Promise rejected with value: [
  [Error: ENOENT: no such file or directory, lstat 'C:\nodejs\blog_api\node_modules\@knuckleswtf\scribe\resources\images'] {
    errno: -4058,
    code: 'ENOENT',
    syscall: 'lstat',
    path: 'C:\\nodejs\\blog_api\\node_modules\\@knuckleswtf\\scribe\\resources\\images'
  }
]
    at process.<anonymous> (C:\nodejs\blog_api\node_modules\hard-rejection\index.js:15:12)
    at process.emit (events.js:375:28)
    at processEmit [as emit] (C:\nodejs\blog_api\node_modules\signal-exit\index.js:175:34)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
instead of...
done

**Screenshots or stack traces:**
![image](https://user-images.githubusercontent.com/46464883/134093714-25ac93bf-9f9e-4b97-b289-a48f321c9b8c.png)

**My environment:**
- Node.js version (from `node -v`): 14.17.2
- Framework (Adonis/Express/Restify):Express 4.17.1
- Framework version (from `npm list @adonisjs/core` or `npm list express` or `npm list restify`): npm list express : express@4.17.1
- Scribe version (from `npm list @knuckleswtf/scribe`):2.0.0

**My Scribe config (minus the comments):**

**Additional info:**

**Comment by abduljeleelng** [comment]
Hello team, @shalvah any help on this

**Comment by shalvah** [comment]
Can you try updating to 2.0.1? Should be fixed now.

**Comment by abduljeleelng** [comment]
Thanks, @shalvah, I will try the new version

**Comment by abduljeleelng** [comment]
Hello @shalvah, the error still persists

I have updated the package to "@knuckleswtf/scribe-express": "^2.0.1"

![image](https://user-images.githubusercontent.com/46464883/134668062-38ffe220-e411-4b2a-9c57-136c439f9869.png)

**Comment by shalvah** [comment]
That's not the same error. You didn't even look at the error message. It's because you're running a wrong command. It's `npx scribe generate` (space, not colon). And you're missing a flag too. You should really pay attention to the docs.

**Comment by abduljeleelng** [comment]
Thank @shalvah, it is fine now
