### ISSUE TITLE
AdonisJS v5 ?

### ISSUE THREAD

**Issue by Julien-R44** [knuckleswtf/scribe-js#13]
Hello, first of all thank you for this library 🚀
Is the support of Adonis V5 planned ? In progress ? Do you need help with this? 
I use the version for Laravel and I would love to use it for my projects with Adonis as well. 
Thanks

**Comment by shalvah** [comment]
No, it isn't.

Unfortunately, I've scaled back development on this project for a couple reasons:
1. Supporting multiple frameworks is really difficult and not worth the pain. In retrospect, that was a mistake. Would have been easier to stick with one (definitely NOT Express).
2. Few JS frameworks have the kind of conventions and setup that Laravel has that makes Scribe work so well with it (eg API resources, globalised config, Artisan-like commands that hook into your app state). Some of these exist, bit they aren't widely used.
3. (For Adonis v5 specifically): I originally planned to support it, but I'm not ready to deal with the juggling of TypeScript and JavaScript code and the whole Babel mess.

I'm open to suggestions, but right now I don't even have the bandwidth to maintain all of these packages, so...😞

**Comment by isocroft** [comment]
Goodday @shalvah ., awesome work with this library.

I ask; will it be possible for you to hand-over maintenance of this package for v4 to me for now ?

I can later come up with a plan to handle support for v5. We can create a new dev/release branch for v5 development or something... Let me know what you think about this

**Comment by shalvah** [comment]
I can add you as a collaborator. Do you have any plans for the current release though?

(Also, I must warn you, it's really a lot of work. Do you want to maintain for all packages, or Adonis only?)

**Comment by isocroft** [comment]
@shalvah cool, I don't have plans for a current release. I have just read through the CHANGE-LOG and i was also looking for roadmap but couldn't find any. There are only 2 issues that aren't releasable soon.

What would constitute the latest release ?

I just want to maintain the Adonis packages only. I am not that free myself
