### ISSUE TITLE
Doc block for parent route

### ISSUE THREAD

**Issue by dev-lere** [knuckleswtf/scribe-js#14]
- [x] I've read the [documentation](https://scribe-js.rtfd.io) and I can't find details on how to achieve this.

- [ ]  All endpoints have the "lang" param. 
How do i specify the details and example for it generally without adding it to every route doc block?
Also scribe generates random value for it on every route

<img width="321" alt="Screenshot 2022-02-16 at 2 59 00 PM" src="https://user-images.githubusercontent.com/95657211/154279687-7a3965bf-3355-459b-8be2-0980813c0165.png">

**Comment by shalvah** [comment]
Except for metadata like group and auth status, Scribe doesn't do inheritance well. Your best bet is to create a custom strategy. It's only a few lines of code, and the example in the docs is quite similar to your use case. You can use this to add the parameter to all your endpoints as well as set a value for it.

https://scribe.knuckles.wtf/laravel/advanced/plugins

**Comment by dev-lere** [comment]
Is there a nodejs example for writing custom strategy?

**Comment by shalvah** [comment]
Whoops. I did not notice that this is the JS repo, and I sent you a link to the Laravel docs.

Sorry, custom strategies are not currently supported in Scribe JS.


Also: https://github.com/knuckleswtf/scribe-js/issues/13#issuecomment-948653568

**Comment by dev-lere** [comment]
Thank you
