### ISSUE TITLE
Missing license?

### ISSUE THREAD

**Issue by DanMossa** [knuckleswtf/scribe-js#7]
- [x] I've read the [documentation](https://scribe-js.rtfd.io) and I can't find details on how to achieve this.

Hello! I would love for you to go ahead and add a license your software!

https://choosealicense.com/

Most OSS like this one tend to be MIT

Thanks :)

**Comment by shalvah** [comment]
https://github.com/knuckleswtf/scribe-js/commit/abdf4605b9c088a6af7d0e305c7e26d3d0def9b3
