### ISSUE TITLE
Examples of request body are not generated

### ISSUE THREAD

**Issue by hyungwang** [knuckleswtf/scribe-js#8]
**What happened?**
 After generating the documentation I noticed that request body examples are missing

**Screenshots or stack traces:**

<img width="1156" alt="Screenshot 2021-08-30 at 12 27 07 PM" src="https://user-images.githubusercontent.com/13274118/131336704-1b5c7bf0-25f7-4860-be36-619a9bb92a35.png">

**My environment:**
- Node.js version (from `node -v`): v14.16.1
- Framework (Adonis/Express/Restify): Express
- Framework version (from `npm list @adonisjs/core` or `npm list express` or `npm list restify`): express@4.17.1 
- Scribe version (from `npm list @knuckleswtf/scribe`): @knuckleswtf/scribe@1.8.5 

**My Scribe config (minus the comments):**

**Additional info:**
The openapi.yaml that is generated has examples in it but the postman collections generate doesn't

**Comment by shalvah** [comment]
My guess is that it's because your parameters are optional (although that shouldn't happen). What happens if you mark some as `required`?

**Comment by hyungwang** [comment]
> My guess is that it's because your parameters are optional (although that shouldn't happen). What happens if you mark some as `required`?

No example in any of the endpoints.

The endpoint in the screenshot above has all parameters as required.

The openapi.yaml has examples but the  collection.json doesnt

**Comment by shalvah** [comment]
Can you post your docblock?

**Comment by hyungwang** [comment]
`const router = Router();

/**
 * Signup
 *
 * @unauthenticated
 * @group Authentication
 * @groupDescription user authentication endpoints
 *
 * @bodyParam {string} firstName required min:2
 * @bodyParam {string} lastName required min:2
 * @bodyParam {string} email required
 * @bodyParam {string} callingCode required Country's calling code. Example: +234
 * @bodyParam {string} phone required min:8 Example: 8180066785
 * @bodyParam {string} city required
 * @bodyParam {string} province required
 * @bodyParam {string} country required
 */
router.post("/signup", customerSignupPolicy, customerSignup);`

**Comment by hyungwang** [comment]
@shalvah Is the above correct?

**Comment by shalvah** [comment]
Yes, I think you're correct thus far. Sorry, I'm no longer working on v1. Tested this on v2 and it's fine. Should be releasing v2 on or before Tuesday.

**Comment by hyungwang** [comment]
Ok then. I look forward to using V2. 

Thank you boss

**Comment by shalvah** [comment]
Hi, v2 is now out. Take it for a spin, and let me know if there's a problem. Docs: https://scribe.knuckles.wtf/nodejs
